M48
; DRILL file {KiCad 8.0.1} date 2024-04-11T22:43:05-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-11T22:43:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X0.0236Y-0.2996
X0.0236Y-0.5272
T2
X0.1839Y-1.122
X0.1839Y-1.2402
M30
